const productTypes = {
  VIEW_ALL_PRODUCTS: "VIEW_ALL_PRODUCTS",
  VIEW_FEATURED_PRODUCTS: "VIEW_FEATURED_PRODUCTS",
  ADD_PRODUCTS: "ADD_PRODUCTS",
  DECREASE_PRODUCT: "DECREASE_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT"
};

export default productTypes;
